version: "3.9"
services:
  app:
    image: node:alpine
    container_name: app
    build: .
    restart: always
    tty: true
    env_file:
    - .env
    ports:
    - ${APP_PORT}:${APP_PORT}
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: npm start
